export const OPEN_MAIN_MENU = 'OPEN_MAIN_MENU';
export const CLOSE_MAIN_MENU = 'CLOSE_MAIN_MENU';
export const OPEN_HOST_PEER_GAME = 'OPEN_HOST_PEER_GAME';
export const CLOSE_HOST_PEER_GAME = 'CLOSE_HOST_PEER_GAME';
