export const OPEN_HOST_PEER_GAME = 'OPEN_HOST_PEER_GAME';
export const CLOSE_HOST_PEER_GAME = 'CLOSE_HOST_PEER_GAME';
export const OPEN_JOIN_PEER_GAME = 'OPEN_JOIN_PEER_GAME';
export const CLOSE_JOIN_PEER_GAME = 'CLOSE_JOIN_PEER_GAME';
